# theme: jekyll-theme-minimal
title: "Hsu Shun Lae - Cybersecurity Portfolio"
description: "Blue Team • Red Team • Cloud Security • Threat Hunting"
baseurl: "" # keep empty for user.github.io repo; else "/repo-name"
url: "https://HsuShunLae.github.io"
source: . 
